---
apiVersion: v1
kind: Secret
metadata:
  name: thisisaverylongusernametest-poi-gateway-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/rhdh-ms/thisisaverylongusernametest-gateway-gitops
